captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
jwt:
  signing-key: rku1S6ybEHX5WnvfDHdE2TtpX2Mu2NjT
  encing-key: 
  expires-time: 604800
  buffer-time: 86400
local:
  path: uploads/file
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: tenancy
  username: root
  password: Chindeo
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: Chindeo
system:
  env: dev
  addr: 8089
  db-type: mysql
  use-multipoint: false
timer:
  start: false
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
zap:
  level: info
  format: console
  prefix: '[OP-ONLINE]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
